services:
  - type: web
    name: weather-ai-agent
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: OPENWEATHERMAP_API_KEY
        sync: false
      - key: GOOGLE_API_KEY
        sync: false
      - key: DEBUG
        value: false